import React from 'react';

export function Campfire(): JSX.Element {
  return (
    <div className='relative left-[-100px]'>
      {/** Logs */}
      <div
        className='
          relative
          before:absolute
          before:left-0
          before:top-0
          before:w-[200px]
          before:h-[40px]
          before:bg-[#2e201c]
          before:rounded-[10px]
          before:rotate-[20deg]
          before:z-[10]
          after:absolute
          after:left-0
          after:top-0
          after:w-[200px]
          after:h-[40px]
          after:bg-[#402e28]
          after:rotate-[-20deg]
          after:rounded-[10px]
          after:z-[10]
        '
      ></div>
      {/** Fire */}
      <div
        className='
          absolute
          left-[60px]
          top-[-80px]
          w-[50px]
          h-[50px]
          bg-[#c78642]
          rotate-[45deg]
          rounded-[10px]
          duration-200
          origin-center
          animate-firePulseThree
        '
      ></div>
      <div
        className='
          absolute
          left-[50px]
          top-[-90px]
          w-[100px]
          h-[100px]
          bg-[#d4a959]
          rotate-[45deg]
          rounded-[10px]
          duration-200
          origin-center
          animate-firePulseTwo
        '
      ></div>
      <div
        className='
          absolute
          left-[45px]
          top-[-90px]
          w-[110px]
          h-[110px]
          bg-[#ebdb73]
          rotate-[45deg]
          rounded-[10px]
          duration-200
          origin-center
          animate-firePulseOne
        '
      ></div>
      {/** Shadow */}
      <div
        className='
          absolute
          left-[-10px]
          top-[50px]
          w-[250px]
          h-[35px]
          rounded-[50%]
          bg-[#10101033]
        '
      ></div>
    </div>
  );
}